apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-volume-claim
  namespace: bootcamp-devops-cf
  labels:
    app: dj-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi