apiVersion: v1
kind: PersistentVolume
metadata:
  name: dj-app-volume
  namespace: bootcamp-devops-cf
  labels:
    type: local
    app: dj-app
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/dj-app