apiVersion: v1
kind: Service
metadata:
  name: dj-app-service
  namespace: bootcamp-devops-cf
spec:
  type: NodePort
  selector:
    app: dj-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000